import { trpc } from "@/lib/trpc";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Check, ChevronDown, CircleHelp, Database, FileCheck2, Flag, Gauge, Loader2, MessageSquareText, RefreshCw, ShieldCheck, Sparkles, X } from "lucide-react";

const stages = ["Data", "Analysis", "Insight", "Recommendation", "Action"];
const suggestedQuestions = [
  "What happened to revenue in the last two months?",
  "Why did CMP-001's performance decline?",
  "Which campaign has the highest acquisition cost?",
  "What caused the jump in conversions in April?",
  "Which clients have gone inactive, and when?",
  "Is there anything unusual in the North region this quarter?",
];

function Badge({ children, tone = "slate" }: { children: React.ReactNode; tone?: "slate" | "green" | "amber" | "red" | "blue" }) {
  return <span className={`status-badge status-${tone}`}>{children}</span>;
}
function SectionTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) {
  return <div className="section-title"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{detail && <p>{detail}</p>}</div>;
}
function severityTone(severity: string) { return severity === "blocking" ? "red" : severity === "warning" ? "amber" : "blue"; }
function formatValue(value: number | null, unit: string) { if (value === null) return "—"; if (unit === "percent") return `${(value * 100).toFixed(1)}%`; if (unit === "money") return `$${value.toLocaleString("en-US", { maximumFractionDigits: 0 })}`; return value.toLocaleString("en-US", { maximumFractionDigits: 1 }); }
function Trend({ points, unit }: { points: Array<{ label?: string; value: number | null }>; unit: string }) {
  const values = points.map(point => point.value ?? 0); const max = Math.max(...values, 1); const min = Math.min(...values, 0); const range = Math.max(max - min, 0.001);
  return <div className="trend-wrap"><div className="trend-bars">{points.map((point, index) => <div className="trend-item" key={`${point.label}-${index}`}><div className="trend-bar-track"><div className="trend-bar" style={{ height: `${Math.max(8, ((point.value ?? 0) - min) / range * 100)}%` }} /></div><span>{point.label}</span></div>)}</div><div className="trend-caption"><span>Jan</span><strong>{formatValue(points.at(-1)?.value ?? null, unit)}</strong><span>Jun</span></div></div>;
}
function EvidenceTable({ rows }: { rows: Record<string, string | null>[] }) {
  if (!rows.length) return <div className="empty-state">No evidence rows are available for this selection.</div>;
  const columns = Object.keys(rows[0]).slice(0, 6);
  return <div className="table-scroll"><table><thead><tr>{columns.map(column => <th key={column}>{column.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.slice(0, 20).map((row, index) => <tr key={index}>{columns.map(column => <td key={column}>{row[column] || "—"}</td>)}</tr>)}</tbody></table></div>;
}

export default function Home() {
  const { data, isLoading, isError, refetch } = trpc.mis.snapshot.useQuery();
  const utils = trpc.useUtils();
  const [activeStage, setActiveStage] = useState(0);
  const [selectedAnomalyId, setSelectedAnomalyId] = useState<string | undefined>();
  const [insight, setInsight] = useState<any>();
  const [recommendation, setRecommendation] = useState<any>();
  const [decision, setDecision] = useState<"accepted" | "edited" | "rejected">("accepted");
  const [recommendationText, setRecommendationText] = useState("");
  const [rationale, setRationale] = useState("");
  const [question, setQuestion] = useState("");
  const [questionResult, setQuestionResult] = useState<any>();
  const [showHistory, setShowHistory] = useState(false);
  const [showAllIssues, setShowAllIssues] = useState(false);
  const [toast, setToast] = useState("");
  const selectedAnomaly = useMemo(() => data?.anomalies.find(item => item.id === selectedAnomalyId) ?? data?.anomalies[0], [data, selectedAnomalyId]);
  const insightMutation = trpc.mis.insight.useMutation({ onSuccess: result => { setInsight(result); setActiveStage(2); setToast(result.fallback ? "AI guardrail returned a deterministic fallback." : "Evidence-bounded insight ready."); } });
  const recommendationMutation = trpc.mis.recommendation.useMutation({ onSuccess: result => { setRecommendation(result); setRecommendationText(result.recommendation); setActiveStage(3); setToast(result.fallback ? "Recommendation fallback used safely." : "One recommendation ready for review."); } });
  const decisionMutation = trpc.mis.decision.useMutation({ onSuccess: () => { void utils.mis.snapshot.invalidate(); setActiveStage(4); setToast("Decision logged with evidence hash and prompt metadata."); setRationale(""); } });
  const questionMutation = trpc.mis.question.useMutation({ onSuccess: result => setQuestionResult(result) });
  useEffect(() => { if (data?.anomalies[0] && !selectedAnomalyId) setSelectedAnomalyId(data.anomalies[0].id); }, [data, selectedAnomalyId]);
  useEffect(() => { if (toast) { const timer = window.setTimeout(() => setToast(""), 3600); return () => window.clearTimeout(timer); } }, [toast]);

  const runInsight = () => { if (selectedAnomaly) insightMutation.mutate({ anomalyId: selectedAnomaly.id }); };
  const runRecommendation = () => { if (selectedAnomaly && insight) recommendationMutation.mutate({ anomalyId: selectedAnomaly.id, insight }); };
  const submitDecision = () => { if (!selectedAnomaly || !recommendation || !rationale.trim()) return; decisionMutation.mutate({ anomalyId: selectedAnomaly.id, decision, recommendation: recommendationText.trim(), rationale: rationale.trim(), evidenceHash: recommendation.evidenceHash, promptVersion: recommendation.promptVersion }); };

  if (isLoading) return <div className="app-shell loading-shell"><Loader2 className="spin" size={24} /><span>Loading the sample MIS dataset…</span></div>;
  if (isError || !data) return <div className="app-shell"><div className="error-state"><AlertTriangle size={28} /><h1>Could not load the sample dataset</h1><p>The deterministic analysis service is unavailable. Try loading the fixture again.</p><button className="button button-primary" onClick={() => refetch()}><RefreshCw size={16} /> Retry</button></div></div>;

  const visibleIssues = showAllIssues ? data.issues : data.issues.slice(0, 5);
  const blockingCount = data.issues.filter(issue => issue.severity === "blocking").length;

  return <div className="app-shell">
    <div className="sample-banner"><Database size={16} /><strong>Sample Data</strong><span>Frozen synthetic CSV fixtures · structure matches real MIS exports · Jan–Jun 2026</span><Badge tone="blue">Simulated source</Badge></div>
    <header className="topbar"><div className="brand-mark"><div className="brand-icon"><Gauge size={19} /></div><div><div className="brand-name">MIS Copilot</div><div className="brand-subtitle">Evidence before action</div></div></div><div className="topbar-actions"><Badge tone="green"><span className="dot" /> Implemented MVP</Badge><button className="quiet-button" onClick={() => setShowHistory(value => !value)}><RefreshCw size={15} /> Decision history</button></div></header>
    <main className="content-wrap">
      <section className="hero"><div><div className="eyebrow">Marketing intelligence / controlled workflow</div><h1>Turn KPI movement into a <em>defensible</em> decision.</h1><p>Load a small MIS slice, isolate what changed, show the evidence, and let a human decide what happens next. The AI interprets validated evidence; it never calculates the numbers.</p></div><div className="hero-note"><ShieldCheck size={18} /><div><strong>Guardrail principle</strong><span>Every insight is tied to an evidence hash and checked for unsupported numbers.</span></div></div></section>
      <nav className="stage-nav" aria-label="Workflow stages">{stages.map((stage, index) => <button key={stage} className={`stage-step ${index === activeStage ? "active" : ""} ${index < activeStage ? "complete" : ""}`} onClick={() => setActiveStage(index)}><span className="stage-number">{index < activeStage ? <Check size={14} /> : index + 1}</span><span>{stage}</span>{index < stages.length - 1 && <ArrowRight size={14} className="stage-arrow" />}</button>)}</nav>

      {activeStage === 0 && <section className="stage-section"><SectionTitle eyebrow="Stage 01 / Data" title="The source is visible before the story begins." detail="All six fixture tables are loaded server-side and checked before analysis." /><div className="source-grid">{data.sourceSummary.map(source => <div className="source-card" key={source.source}><div className="source-icon"><FileCheck2 size={17} /></div><div><strong>{source.source}</strong><span>{source.file}</span></div><b>{source.rows}<small> rows</small></b></div>)}</div><div className="quality-layout"><div className="panel quality-panel"><div className="panel-heading"><div><div className="eyebrow">Quality report</div><h3>{data.issues.length} issues detected intentionally</h3></div><Badge tone={blockingCount ? "red" : "green"}>{blockingCount ? `${blockingCount} blocking` : "No blockers"}</Badge></div><div className="issue-list">{visibleIssues.map(issue => <div className="issue-row" key={issue.id}><Badge tone={severityTone(issue.severity)}>{issue.severity}</Badge><div><strong>{issue.code.replaceAll("_", " ")}</strong><span>{issue.message}</span></div><small>{issue.source} · row {issue.row}</small></div>)}</div><button className="text-button" onClick={() => setShowAllIssues(value => !value)}>{showAllIssues ? "Show fewer issues" : `Show all ${data.issues.length} issues`} <ChevronDown size={15} /></button></div><div className="panel source-policy"><div className="eyebrow">Analysis policy</div><h3>Nothing questionable is hidden.</h3><p>Blocking records are excluded from affected calculations. Warnings remain visible with a caveat. Informational findings are preserved for review.</p><div className="policy-line"><span className="policy-dot red" /> Blocking <small>excludes affected record</small></div><div className="policy-line"><span className="policy-dot amber" /> Warning <small>visible caveat</small></div><div className="policy-line"><span className="policy-dot blue" /> Informational <small>review context</small></div><button className="button button-primary full-width" onClick={() => setActiveStage(1)}>Continue to analysis <ArrowRight size={16} /></button></div></div></section>}

      {activeStage === 1 && <section className="stage-section"><SectionTitle eyebrow="Stage 02 / Analysis" title="The math stays deterministic and inspectable." detail="Every KPI shows its formula, numerator, denominator, and monthly trend." /><div className="kpi-grid">{data.kpis.map(kpi => <div className="kpi-card" key={kpi.id}><div className="kpi-top"><span>{kpi.label}</span><span className={kpi.delta !== null && kpi.delta !== undefined && kpi.delta < 0 ? "negative" : "positive"}>{kpi.deltaDisplay}</span></div><div className="kpi-value">{kpi.displayValue}</div><div className="formula"><code>{kpi.formula}</code><span>{kpi.numerator}</span><span>{kpi.denominator}</span></div><Trend points={kpi.trend} unit={kpi.unit} /></div>)}</div><div className="analysis-bottom"><div className="panel anomaly-picker"><div className="panel-heading"><div><div className="eyebrow">Rule-based review queue</div><h3>{data.anomalies.length} flags ready for investigation</h3></div><Badge tone="amber">No ML prediction</Badge></div><div className="anomaly-list">{data.anomalies.map(anomaly => <button key={anomaly.id} onClick={() => setSelectedAnomalyId(anomaly.id)} className={`anomaly-item ${selectedAnomaly?.id === anomaly.id ? "selected" : ""}`}><span className={`severity-marker ${anomaly.severity}`} /><div><strong>{anomaly.title}</strong><span>{anomaly.metric} · {anomaly.rule}</span></div><ArrowRight size={16} /></button>)}</div><button className="button button-primary" onClick={() => { setActiveStage(2); if (!insight) runInsight(); }}>Investigate selected flag <ArrowRight size={16} /></button></div><div className="panel explain-panel"><div className="eyebrow">Selected flag</div><h3>{selectedAnomaly?.title}</h3><p>{selectedAnomaly?.comparison}</p><div className="evidence-callout"><Flag size={16} /><span>Evidence is capped at 20 rows per packet and shown again in Insight.</span></div><button className="button button-ghost" onClick={() => setActiveStage(2)}>View evidence <ArrowRight size={16} /></button></div></div></section>}

      {activeStage === 2 && <section className="stage-section"><SectionTitle eyebrow="Stage 03 / Insight" title="Interpretation follows the evidence." detail="The model receives only this flagged metric's evidence packet—not the full dataset." /><div className="insight-layout"><div className="panel evidence-panel"><div className="panel-heading"><div><div className="eyebrow">Evidence packet</div><h3>{selectedAnomaly?.title}</h3></div><Badge tone="blue">Hash {selectedAnomaly?.evidenceHash}</Badge></div><p className="muted">{selectedAnomaly?.comparison}</p><EvidenceTable rows={selectedAnomaly?.evidence ?? []} /></div><div className="panel ai-panel"><div className="ai-label"><Sparkles size={15} /> AI interpretation</div>{!insight && !insightMutation.isPending && <div className="empty-state"><MessageSquareText size={23} /><strong>Ready to inspect the selected flag.</strong><span>The model will be constrained to the evidence packet on the left.</span><button className="button button-primary" onClick={runInsight}>Generate evidence-bound insight <Sparkles size={15} /></button></div>}{insightMutation.isPending && <div className="empty-state"><Loader2 className="spin" size={22} /><strong>Reading evidence packet…</strong><span>Validating structured output and numerical claims.</span></div>}{insight && <div className="ai-result"><div className="result-label">Diagnosis</div><p className="lead-copy">{insight.diagnosis}</p><div className="result-label">Most likely interpretation</div><p>{insight.likelyReason}</p><div className="result-columns"><div><strong>Supporting evidence</strong><ul>{insight.supportingEvidence.map((item: string) => <li key={item}>{item}</li>)}</ul></div><div><strong>What would confirm it</strong><ul>{insight.dataToConfirm.map((item: string) => <li key={item}>{item}</li>)}</ul></div></div><div className="limitation"><ShieldCheck size={15} /><span>{insight.limitations.join(" ")}</span></div><div className="ai-meta"><Badge tone={insight.fallback ? "amber" : "green"}>{insight.fallback ? "Deterministic fallback" : "AI checked"}</Badge><span>Evidence hash: {insight.evidenceHash}</span>{insight.validation && <span>Validation note: {insight.validation}</span>}</div><button className="button button-primary full-width" onClick={runRecommendation} disabled={recommendationMutation.isPending}>{recommendationMutation.isPending ? <><Loader2 className="spin" size={16} /> Preparing one recommendation…</> : <>Continue to recommendation <ArrowRight size={16} /></>}</button></div>}</div></div></section>}

      {activeStage === 3 && <section className="stage-section"><SectionTitle eyebrow="Stage 04 / Recommendation" title="One recommendation. Clearly labelled. Still yours to decide." detail="No auto-execution. The recommendation is generated from the same evidence hash used for the insight." /><div className="recommendation-layout"><div className="panel evidence-panel"><div className="eyebrow">Same evidence packet</div><h3>{selectedAnomaly?.title}</h3><p className="muted">{selectedAnomaly?.comparison}</p><EvidenceTable rows={selectedAnomaly?.evidence ?? []} /></div><div className="panel recommendation-panel">{!recommendation && <div className="empty-state"><Loader2 className="spin" size={22} /><strong>Recommendation not generated yet.</strong><button className="button button-primary" onClick={runRecommendation}>Generate one recommendation</button></div>}{recommendation && <><div className="recommendation-label"><span>Recommendation</span><Badge tone={recommendation.fallback ? "amber" : "green"}>{recommendation.fallback ? "Safe fallback" : "AI checked"}</Badge></div><textarea className="recommendation-editor" value={recommendationText} onChange={event => setRecommendationText(event.target.value)} aria-label="Recommendation text" /><div className="recommendation-facts"><div><span>Owner</span><strong>{recommendation.ownerRole}</strong></div><div><span>Time horizon</span><strong>{recommendation.timeHorizon}</strong></div><div><span>Success check</span><strong>{recommendation.successCheck}</strong></div></div><div className="evidence-callout"><ShieldCheck size={16} /><span>Evidence hash invariant: {recommendation.evidenceHash === insight?.evidenceHash ? "matched" : "blocked"}</span></div><button className="button button-primary full-width" onClick={() => setActiveStage(4)}>Review human decision <ArrowRight size={16} /></button></>}</div></div></section>}

      {activeStage === 4 && <section className="stage-section"><SectionTitle eyebrow="Stage 05 / Action" title="The human is the last step." detail="Accept, edit, or reject the recommendation. A rationale is required before logging." /><div className="action-layout"><div className="panel decision-panel"><div className="decision-header"><div><div className="eyebrow">Decision form</div><h3>What should happen next?</h3></div><Badge tone="blue">Human decision required</Badge></div><div className="decision-options">{(["accepted", "edited", "rejected"] as const).map(option => <button key={option} className={`decision-option ${decision === option ? "selected" : ""}`} onClick={() => setDecision(option)}><span>{option === "accepted" ? <Check size={17} /> : option === "edited" ? <RefreshCw size={17} /> : <X size={17} />}</span><div><strong>{option === "accepted" ? "Accept" : option === "edited" ? "Edit & accept" : "Reject"}</strong><small>{option === "rejected" ? "Do not proceed with this action" : "Log this recommendation as the chosen next step"}</small></div></button>)}</div><label className="field-label">Recommendation text <span>editable</span><textarea className="recommendation-editor" value={recommendationText} onChange={event => setRecommendationText(event.target.value)} /></label><label className="field-label">Rationale <span className="required">required</span><textarea className="rationale-input" value={rationale} onChange={event => setRationale(event.target.value)} placeholder="Explain why you accepted, edited, or rejected this recommendation…" /></label>{!rationale.trim() && <div className="form-hint"><AlertTriangle size={14} /> A rationale is required before the decision can be submitted.</div>}<button className="button button-primary full-width" disabled={!rationale.trim() || decisionMutation.isPending} onClick={submitDecision}>{decisionMutation.isPending ? <><Loader2 className="spin" size={16} /> Logging decision…</> : <>Log human decision <Check size={16} /></>}</button></div><div className="panel log-panel"><div className="eyebrow">Decision trace</div><h3>What will be logged</h3><div className="trace-item"><span>Evidence hash</span><strong>{recommendation?.evidenceHash ?? selectedAnomaly?.evidenceHash}</strong></div><div className="trace-item"><span>Prompt version</span><strong>{recommendation?.promptVersion ?? "v1.0"}</strong></div><div className="trace-item"><span>Source rows</span><strong>Max 20, visible above</strong></div><div className="trace-item"><span>Action mode</span><strong>Manual only</strong></div><button className="button button-ghost full-width" onClick={() => setShowHistory(true)}>Open decision history</button></div></div></section>}

      <section className="qa-section"><SectionTitle eyebrow="Bounded Q&A" title="Ask the questions this dataset can answer." detail="Deterministic lookup first. Unsupported questions stay unsupported." /><div className="qa-input-row"><input value={question} onChange={event => setQuestion(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && question.trim()) questionMutation.mutate({ question }); }} placeholder="Try: What happened to revenue in the last two months?" /><button className="button button-primary" disabled={!question.trim() || questionMutation.isPending} onClick={() => questionMutation.mutate({ question })}>{questionMutation.isPending ? <Loader2 className="spin" size={16} /> : <MessageSquareText size={16} />} Ask</button></div><div className="question-chips">{suggestedQuestions.map(item => <button key={item} onClick={() => { setQuestion(item); questionMutation.mutate({ question: item }); }}>{item}</button>)}</div>{questionResult && <div className={`qa-result ${questionResult.supported ? "" : "unsupported"}`}><div className="qa-result-head"><Badge tone={questionResult.supported ? "green" : "amber"}>{questionResult.supported ? "Validated answer" : "Not supported"}</Badge><span>{questionResult.intent}</span></div><p>{questionResult.supported ? questionResult.answer : "This MVP only answers the six validated examples below. It does not query the entire dataset or generate SQL."}</p>{!questionResult.supported && <div className="question-chips">{questionResult.examples.map((item: string) => <button key={item} onClick={() => { setQuestion(item); questionMutation.mutate({ question: item }); }}>{item}</button>)}</div>}{questionResult.supported && <><div className="result-label">Answer evidence</div><EvidenceTable rows={questionResult.evidence} /></>}</div>}</section>
    </main>
    {showHistory && <div className="history-drawer"><div className="drawer-head"><div><div className="eyebrow">Audit trail</div><h2>Human decision history</h2></div><button className="icon-button" onClick={() => setShowHistory(false)}><X size={18} /></button></div>{data.decisions.length === 0 ? <div className="empty-state"><RefreshCw size={23} /><strong>No decisions logged yet.</strong><span>Complete the workflow to create the first trace.</span></div> : data.decisions.map(item => <div className="history-item" key={item.id}><div className="history-item-top"><Badge tone={item.decision === "rejected" ? "red" : "green"}>{item.decision}</Badge><span>{new Date(item.createdAt).toLocaleString()}</span></div><strong>{item.recommendation}</strong><p>{item.rationale}</p><small>Evidence {item.evidenceHash} · prompt {item.promptVersion}</small></div>)}</div>}
    {toast && <div className="toast"><Check size={15} /> {toast}</div>}
  </div>;
}
